### ISSUE TITLE
Loading HRTF from memory

### ISSUE THREAD

**Issue by GitGhillie** [andreiltd/sofar#2]
Hi! Thank you for making this crate! With the example provided in the readme it's been really easy to setup.

Currently I'm trying to load a HRTF from memory so I can embed it into my binary/dylib just like Steam Audio. However, it seems like [mysofa_open_data](https://github.com/hoene/libmysofa/blob/2297dd8224ccf42882a2546f2c7ee02e7ab0d1ba/src/hrtf/mysofa.h#L186) is not exposed yet.

Is this something you would be open to support?

**Comment by andreiltd** [comment]
Sure, this makes sense. Could you give this branch a try and see if it works for you? https://github.com/andreiltd/sofar/pull/3

**Comment by GitGhillie** [comment]
Seems to be working like a charm on both Windows and Linux!

**Comment by andreiltd** [comment]
The crates should be now published to crates.io.

**Comment by GitGhillie** [comment]
Can confirm, thanks!
